#include "target.h"

// local public samplers: "adpe", "alkh", "amlo", "barn", "bcir", "brli", "chad", "chak", "chl1", "chlk", "cmnt", "cobs", "dits", "dlig", "dtrk", "face", "fena", "flos", "glbb", "glo3", "glo4", "glo5", "glo7", "glof", "glpg", "glwb", "grey", "lod1", "logo", "mlbb", "mlpa", "mout", "mrel", "nets", "nett", "newg", "nite", "shaw", "shd0", "shd3", "teet", "trl2", "twii", "vitr", "war2"
// local public/global samplers: "arce", "arch", "bar2", "barl", "bd04", "brid", "bulb", "cem1", "cem2", "cem5", "cemb", "cemd", "cemh", "cemv", "conc", "dayd", "deck", "dirs", "fen1", "fen3", "fen5", "flod", "frum", "gexi", "glo0", "glo1", "glo2", "gloo", "glow", "gree", "grwl", "haut", "hflo", "hlwy", "lamp", "larc", "lgr1", "litb", "lnk3", "msca", "nete", "nt03", "pasa", "pen1", "sco2", "shad", "sl1", "terr", "tplo", "tr02", "tr07", "tr08", "tr0b", "tr18", "trbl", "tre1", "tree", "trg0", "trg1", "trg3", "trg6", "trg9", "trga", "trs5", "turf", "uni2", "uni3", "walb", "walh", "war1", "war3", "warm", "warn", "wbar", "wdw1", "wdws", "wl01", "wntk", "wrn1"
Shader shaders_MVP2005[18] = {
    // MVPAdditiveForwardTexture, hash 2750542700
    // in files (266): camaligned.ord, colouradd.ord, mstadium.ord
    { "MVPAdditiveForwardTexture", 6, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, ";SetTransparencyMethod=EAGL::TM_ALPHA;SetAlphaTestEnable=false;SetAlphaBlendMode=EAGL::ABM_ADD" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPCrowdScrollTexture, hash 498645562
    // in files (979): crowd.ord, remcrowd0.ord, remcrowd1.ord, remcrowd2.ord, remcrowd3.ord, remcrowd4.ord, remcrowd5.ord
    { "MVPCrowdScrollTexture", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 10 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 14 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 18 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::FogParameters,
    Shader::CrowdState,
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPField, hash 4061265185
    // in files (1403): mfield0.ord, mfield1.ord, mfield2.ord, removable.ord, track.ord
    { "MVPField", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetAlphaBlendMode=EAGL::ABM_BLEND;SetAlphaTestEnable=true;SetAlphaTestMethod=EAGL::ATM_GREATER;SetDepthTestMethod=EAGL::DTM_ALWAYS;SetTransparencyMethod=EAGL::TM_ALPHA" },
    Shader::Sampler0Local, // local public
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPFieldLine, hash 4189768053
    // in files (261): mfield0.ord, mfield1.ord, mfield2.ord
    { "MVPFieldLine", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    Shader::LineNoDepthWriteState,
    Shader::Sampler0Local, // local public
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPFieldTextureAnimation, hash 1611973257
    // in files (2527): mfield0.ord, mfield1.ord, mfield2.ord
    { "MVPFieldTextureAnimation", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 10 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 14 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 18 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetAlphaBlendMode=EAGL::ABM_BLEND;SetAlphaTestEnable=true;SetAlphaTestMethod=EAGL::ATM_GREATER;SetDepthTestMethod=EAGL::DTM_ALWAYS;SetTransparencyMethod=EAGL::TM_ALPHA" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPFieldTextureAnimationAdd, hash 2756015735
    // in files (303): mfield0.ord, mfield1.ord, mfield2.ord
    { "MVPFieldTextureAnimationAdd", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 10 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 14 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 18 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetAlphaBlendMode=EAGL::ABM_ADD;SetAlphaTestEnable=true;SetAlphaTestMethod=EAGL::ATM_GREATER;SetDepthTestMethod=EAGL::DTM_ALWAYS;SetTransparencyMethod=EAGL::TM_ALPHA" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPForwardTexture, hash 1782863496
    // in files (1085): alphablend.ord, lawn.o, mstadium.ord
    { "MVPForwardTexture", 6, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, ";SetTransparencyMethod=EAGL::TM_ALPHA;SetAlphaTestEnable=false;SetAlphaBlendMode=EAGL::ABM_BLEND" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPGlower, hash 2529310735
    // in files (400): net.ord
    { "MVPGlower", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    Shader::GlowerState,
    Shader::Sampler0Local, // local public
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPInstanceCrowd, hash 518156075
    // in files (87): 3dcrowd.ord
    { "MVPInstanceCrowd", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 9, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 10, 4 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { NOP_1, { 10, 4 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x3E0002, 3, 0x350002, 5, 0x4D0002, 6, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { NOP_1, { 10, 4 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x3E0002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    { Shader::RuntimeGeoPrimState, "SetTransparencyMethod=EAGL::TM_OPAQUE;SetAlphaBlendMode=EAGL::ABM_OFF;SetAlphaTestEnable=true;SetAlphaCompareValue=0" },
    Shader::Sampler0, // global
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::InstanceColour,
    Shader::FogParameters,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPInstanceFlag, hash 550608747
    // in files (87): 3dflag.ord
    { "MVPInstanceFlag", 3, { { Shader::Float3, Shader::Position }, { Shader::Float3, Shader::Normal }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 8 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 12 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 16, 28 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 23, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 24 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 28, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 29, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 30, 4 } },
    { SET_STREAM_SOURCE, { 0, 36, 338, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 4 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { NOP_1, { 0 } },
    { NOP_1, { 4 } },
    { NOP_1, { 8 } },
    { NOP_1, { 12 } },
    { NOP_1, { 16, 28 } },
    { NOP_1, { 23, 4 } },
    { NOP_1, { 24 } },
    { NOP_1, { 28, 4 } },
    { NOP_1, { 29, 4 } },
    { NOP_1, { 30, 4 } },
    { NOP_1, { 0, 36, 338, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 36, 338, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 13, 0x330002, 4, 0x340002, 5, 0x3D0002, 6, 0x350002, 9, 0x320003, 7, 1, 0x440001 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER_G, { 0, Shader::Sampler0Size } },
    { NOP_1, { 0 } },
    { NOP_1, { 4 } },
    { NOP_1, { 8 } },
    { NOP_1, { 12 } },
    { NOP_1, { 16, 28 } },
    { NOP_1, { 23, 4 } },
    { NOP_1, { 24 } },
    { NOP_1, { 28, 4 } },
    { NOP_1, { 29, 4 } },
    { NOP_1, { 30, 4 } },
    { NOP_1, { 0, 36, 338, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 36, 338, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 13, 0x330002, 4, 0x340002, 5, 0x3D0002, 6, 0x350002, 9, 0x320003, 7, 1, 0x440001 } }
    },
    {
    Shader::GeometryInfo,
    Shader::RuntimeGeoPrimState,
    Shader::Sampler0, // global
    Shader::ModelViewProjectionMatrix,
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::FlagLightBlock,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::InstanceColour,
    Shader::ZeroOneTwoThree,
    Shader::FogParameters,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPIrradLitTextureFog2x_Skin, hash 2582716941
    // in files (959): c001.ord, c003.ord, c004.ord, c005.ord, c006.ord, c007.ord, c008.ord, c009.ord, c010.ord, c011.ord, c012.ord, c013.ord, c014.ord, c015.ord, c016.ord, c017.ord, c018.ord, c019.ord, c020.ord, c021.ord, c022.ord, c023.ord, c024.ord, c025.ord, c026.ord, c027.ord, c028.ord, c029.ord, c030.ord, c031.ord, c032.ord, c033.ord, c034.ord, c035.ord, c036.ord, c038.ord, c039.ord, c040.ord, c041.ord, c042.ord, c043.ord, c044.ord, c045.ord, c046.ord, c047.ord, c048.ord, c049.ord, c050.ord, c051.ord, c052.ord, c053.ord, c054.ord, c055.ord, c056.ord, c057.ord, c059.ord, c060.ord, c061.ord, c062.ord, c063.ord, c064.ord, c065.ord, c066.ord, c067.ord, c068.ord, c069.ord, c070.ord, c071.ord, c072.ord, c073.ord, c074.ord, c075.ord, c076.ord, c077.ord, c078.ord, c079.ord, c081.ord, c082.ord, c083.ord, c084.ord, c085.ord, c086.ord, c087.ord, c088.ord, c089.ord, c090.ord, c091.ord, c092.ord, c093.ord, c094.ord, c095.ord, c096.ord, c097.ord, c098.ord, c099.ord, c100.ord, c101.ord, c102.ord, c103.ord, c104.ord, c105.ord, c107.ord, c108.ord, c109.ord, c110.ord, c111.ord, c112.ord, c114.ord, c115.ord, c116.ord, c117.ord, c118.ord, c119.ord, c120.ord, c121.ord, c122.ord, c123.ord, c124.ord, c125.ord, c126.ord, c127.ord, c128.ord, c129.ord, c130.ord, c131.ord, c133.ord, c135.ord, c137.ord, c138.ord, c139.ord, c140.ord, c142.ord, c143.ord, c144.ord, c145.ord, c146.ord, c147.ord, c148.ord, c150.ord, c151.ord, c152.ord, c153.ord, c154.ord, c156.ord, c157.ord, c158.ord, c159.ord, c160.ord, c163.ord, c164.ord, c165.ord, c166.ord, c167.ord, c168.ord, c170.ord, c172.ord, c173.ord, c174.ord, c175.ord, c176.ord, c178.ord, c179.ord, c180.ord, c181.ord, c182.ord, c183.ord, c184.ord, c186.ord, c187.ord, c188.ord, c189.ord, c190.ord, c191.ord, c192.ord, c193.ord, c194.ord, c196.ord, c197.ord, c198.ord, c199.ord, c200.ord, c201.ord, c202.ord, c203.ord, c204.ord, c205.ord, c206.ord, c207.ord, c208.ord, c209.ord, c211.ord, c212.ord, c213.ord, c214.ord, c215.ord, c216.ord, c217.ord, c218.ord, c219.ord, c220.ord, c221.ord, c222.ord, c223.ord, c224.ord, c225.ord, c226.ord, c227.ord, c228.ord, c229.ord, c230.ord, c231.ord, c232.ord, c233.ord, c234.ord, c235.ord, c236.ord, c237.ord, c238.ord, c239.ord, c240.ord, c241.ord, c242.ord, c243.ord, c244.ord, c245.ord, c246.ord, c247.ord, c248.ord, c249.ord, c250.ord, c251.ord, c252.ord, c253.ord, c254.ord, c255.ord, c256.ord, c257.ord, c258.ord, c259.ord, c260.ord, c261.ord, c263.ord, c264.ord, c265.ord, c266.ord, c267.ord, c268.ord, c270.ord, c271.ord, c272.ord, c273.ord, c274.ord, c275.ord, c276.ord, c277.ord, c278.ord, c279.ord, c280.ord, c281.ord, c282.ord, c283.ord, c284.ord, c285.ord, c286.ord, c287.ord, c288.ord, c289.ord, c290.ord, c291.ord, c292.ord, c293.ord, c294.ord, c295.ord, c296.ord, c297.ord, c298.ord, c299.ord, c300.ord, c301.ord, c302.ord, c303.ord, c304.ord, c305.ord, c306.ord, c307.ord, c308.ord, c309.ord, c310.ord, c311.ord, c312.ord, c313.ord, c314.ord, c315.ord, c316.ord, c317.ord, c318.ord, c320.ord, c321.ord, c323.ord, c324.ord, c325.ord, c326.ord, c327.ord, c328.ord, c329.ord, c330.ord, c331.ord, c332.ord, c333.ord, c334.ord, c335.ord, c336.ord, c337.ord, c338.ord, c339.ord, c341.ord, c343.ord, c344.ord, c346.ord, c348.ord, c352.ord, c353.ord, c354.ord, c355.ord, c356.ord, c357.ord, c358.ord, c359.ord, c360.ord, c361.ord, c362.ord, c363.ord, c365.ord, c367.ord, c370.ord, c371.ord, c372.ord, c373.ord, c374.ord, c375.ord, c376.ord, c377.ord, c378.ord, c379.ord, c380.ord, c381.ord, c382.ord, c383.ord, c384.ord, c385.ord, c386.ord, c387.ord, c388.ord, c389.ord, c391.ord, c392.ord, c393.ord, c394.ord, c395.ord, c396.ord, c398.ord, c399.ord, c400.ord, c401.ord, c402.ord, c404.ord, c405.ord, c406.ord, c407.ord, c410.ord, c411.ord, c412.ord, c413.ord, c414.ord, c415.ord, c416.ord, c417.ord, c421.ord, c422.ord, c423.ord, c424.ord, c425.ord, c426.ord, c427.ord, c428.ord, c429.ord, c430.ord, c431.ord, c432.ord, c433.ord, c434.ord, c435.ord, c436.ord, c437.ord, c438.ord, c439.ord, c440.ord, c441.ord, c442.ord, c443.ord, c444.ord, c445.ord, c446.ord, c447.ord, c449.ord, c450.ord, c451.ord, c452.ord, c453.ord, c454.ord, c455.ord, c456.ord, c458.ord, c459.ord, c460.ord, c461.ord, c462.ord, c463.ord, c464.ord, c465.ord, c466.ord, c467.ord, c471.ord, c473.ord, c474.ord, c475.ord, c476.ord, c477.ord, c478.ord, c481.ord, c482.ord, c483.ord, c484.ord, c485.ord, c486.ord, c487.ord, c488.ord, c489.ord, c490.ord, c491.ord, c492.ord, c493.ord, c494.ord, c495.ord, c496.ord, c497.ord, c498.ord, c499.ord, c512.ord, c513.ord, c514.ord, c515.ord, c516.ord, c517.ord, c518.ord, c519.ord, c520.ord, c521.ord, c522.ord, c523.ord, c524.ord, c525.ord, c526.ord, c527.ord, c528.ord, c529.ord, c530.ord, c531.ord, c532.ord, c533.ord, c534.ord, c535.ord, c537.ord, c538.ord, c539.ord, c540.ord, c541.ord, c542.ord, c543.ord, c544.ord, c545.ord, c546.ord, c547.ord, c548.ord, c549.ord, c550.ord, c551.ord, c552.ord, c553.ord, c555.ord, c556.ord, c557.ord, c563.ord, c564.ord, c565.ord, c566.ord, c567.ord, c569.ord, c570.ord, c581.ord, c603.ord, c604.ord, c605.ord, c606.ord, g001.ord, g002.ord, g003.ord, g004.ord, g005.ord, g006.ord, g007.ord, g008.ord, g009.ord, g010.ord, g011.ord, g012.ord, g013.ord, g014.ord, g015.ord, g016.ord, g017.ord, g018.ord, g019.ord, g020.ord, g021.ord, g022.ord, g023.ord, g024.ord, g025.ord, g026.ord, g027.ord, g028.ord, g029.ord, g030.ord, g031.ord, g032.ord, g033.ord, g034.ord, g035.ord, g036.ord, g037.ord, g038.ord, g039.ord, g040.ord, g041.ord, g042.ord, g043.ord, g044.ord, g045.ord
    { "MVPIrradLitTextureFog2x_Skin", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color1 }, { Shader::Float3, Shader::Normal }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 }, { Shader::UByte4, Shader::BlendIndices }, { Shader::Float3, Shader::BlendWeight } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_BONE_WEIGHTS, { Shader::VertexWeights3Bones, Shader::VertexWeights2Bones, Shader::VertexWeights1Bone } },
    { SET_ANIMATION_BUFFER, { 0, 512 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 40 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 14, 28 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 21, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 22, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 23, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 24 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 28 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 32 } },
    { NOP_1, {  } },
    { SET_STREAM_SOURCE_SKINNED, { 0, 40, 342, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 5 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_BONE_WEIGHTS, { Shader::VertexWeights3Bones, Shader::VertexWeights2Bones, Shader::VertexWeights1Bone } },
    { SET_ANIMATION_BUFFER, { 0, 512 } },
    { NOP_1, { 0 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 4, 40 } },
    { NOP_1, { 14, 28 } },
    { NOP_1, { 21, 4 } },
    { NOP_1, { 22, 4 } },
    { NOP_1, { 23, 4 } },
    { NOP_1, { 24 } },
    { NOP_1, { 28 } },
    { NOP_1, { 32 } },
    { NOP_1, {  } },
    { NOP_1, { 0, 40, 342, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4B000C, 0, 40, 342, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1, 0x330002, 11, 0x340002, 12, 0x3D0002, 13, 0x320003, 7, 1, 0x440001 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_BONE_WEIGHTS, { Shader::VertexWeights3Bones, Shader::VertexWeights2Bones, Shader::VertexWeights1Bone } },
    { SET_ANIMATION_BUFFER, { 0, 512 } },
    { NOP_1, { 0 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 4, 40 } },
    { NOP_1, { 14, 28 } },
    { NOP_1, { 21, 4 } },
    { NOP_1, { 22, 4 } },
    { NOP_1, { 23, 4 } },
    { NOP_1, { 24 } },
    { NOP_1, { 28 } },
    { NOP_1, { 32 } },
    { NOP_1, {  } },
    { NOP_1, { 0, 40, 342, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4B000C, 0, 40, 342, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1, 0x330002, 11, 0x340002, 12, 0x3D0002, 13, 0x320003, 7, 1, 0x440001 } }
    },
    {
    Shader::GeometryInfo,
    Shader::VertexSkinData,
    Shader::EAGLAnimationBuffer,
    Shader::ModelViewProjectionMatrix,
    { Shader::RuntimeGeoPrimState, ";SetTransparencyMethod=EAGL::TM_ALPHA;SetAlphaBlendMode=EAGL::ABM_BLEND;SetAlphaTestEnable=true;SetAlphaCompareValue=127" },
    Shader::Sampler0Local, // local public
    Shader::IrradLight,
    Shader::Light,
    Shader::ZeroOneTwoThree,
    Shader::FogParameters,
    Shader::GlobalDiffuse,
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::GlobalDiffuse,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPJumbo, hash 1548022844
    // in files (75): jumbo.ord
    { "MVPJumbo", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetTransparencyMethod=EAGL::TM_OPAQUE" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPLoResField, hash 1339504296
    // in files (261): mfield0.ord, mfield1.ord, mfield2.ord
    { "MVPLoResField", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    Shader::GeoPrimState,
    Shader::Sampler0Local, // local public
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPNet, hash 3925174025
    // in files (339): net.ord
    { "MVPNet", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetTransparencyMethod=EAGL::TM_ALPHA;SetAlphaTestEnable=true;SetAlphaCompareValue=20;SetAlphaBlendMode=EAGL::ABM_BLEND" },
    Shader::Sampler0Local, // local public
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPProjectiveShadow, hash 1400859343
    // in files (87): mshadow.ord
    { "MVPProjectiveShadow", 3, { { Shader::Float3, Shader::Position }, { Shader::Float3, Shader::Normal }, { Shader::D3DColor, Shader::Color0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 4 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 8, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 10, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_STREAM_SOURCE, { 0, 28, 82, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 4 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 8, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 10, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_STREAM_SOURCE, { 0, 28, 82, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 4 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 8, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 10, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_STREAM_SOURCE, { 0, 28, 82, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::TextureProjectionMatrix,
    Shader::LocalLightDirection,
    Shader::ZeroOneTwoThree,
    Shader::FogParameters,
    Shader::ProjectiveShadow2State,
    Shader::Sampler0, // global
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPTextureAnimation, hash 980921230
    // in files (1736): alphablend.ord, mstadium.ord, removable.ord, sky0.ord, sky1.ord, sky2.ord, sky3.ord, sky4.ord
    { "MVPTextureAnimation", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 10 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 14 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 18 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, ";SetTransparencyMethod=EAGL::TM_ALPHA;SetAlphaTestEnable=false;SetAlphaBlendMode=EAGL::ABM_BLEND" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPTextureAnimationAdd, hash 4242572329
    // in files (30): colouradd.ord
    { "MVPTextureAnimationAdd", 3, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_L_46, { 4, 4 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 10 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 14 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 18 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { NOP_1, { 5 } },
    { NOP_1, { 9, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 10 } },
    { NOP_1, { 14 } },
    { NOP_1, { 18 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 10, 0x330002, 7, 0x340002, 8, 0x3D0002, 9, 0x350002, 3, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::UVOffset_Layer,
    Shader::UVMatrix_Layer,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, "SetTextureEnable=true;SetAlphaBlendMode=EAGL::ABM_ADD;SetAlphaTestEnable=true;SetAlphaTestMethod=EAGL::ATM_GREATER;SetTransparencyMethod=EAGL::TM_ALPHA" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    },
    // MVPTextureFog, hash 1278677396
    // in files (18733): aple.o, background0.ord, background1.ord, background2.ord, bern.o, bli1.o, bli2.o, cammen.ord, mfield0.ord, mfield1.ord, mfield2.ord, moon.o, mstadium.ord, obj1.o, obj2.o, obj3.o, obj4.o, pla1.o, pla2.o, removable.ord, roof.o, sky0.ord, sky1.ord, sky2.ord, sky3.ord, sky4.ord, tran.o
    { "MVPTextureFog", 6, { { Shader::Float3, Shader::Position }, { Shader::D3DColor, Shader::Color0 }, { Shader::Float2, Shader::Texcoord0 } },
    {
    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 0, -1 } },
    { NOP_1, {  } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 0 } },
    { SET_VERTEX_SHADER_CONSTANT_G, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 5 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 9 } },
    { SET_VERTEX_SHADER_TRANSPOSED_MATRIX, { 13 } },
    { SET_STREAM_SOURCE, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_NO_Z_WRITE, { 3 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } },

    { SETUP_RENDER, { 1, -1 } },
    { NOP_1, {  } },
    { NOP_1, { 0 } },
    { NOP_1, { 4, 4 } },
    { SET_GEO_PRIM_STATE, {  } },
    { SET_SAMPLER, { 0, Shader::Sampler0Size } },
    { NOP_1, { 5 } },
    { NOP_1, { 9 } },
    { NOP_1, { 13 } },
    { NOP_1, { 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, -1, -1 } },
    { SET_INDEX_BUFFER, { 2, -1, -1, Shader::IndexData, Shader::IndexCount } },
    { DRAW_INDEXED_PRIM_AND_END, { 0x4000B, 0, 24, 322, -1, -1, Shader::VertexData, Shader::VertexCount, Shader::VariationsCount, Shader::VertexBufferIndex, 8, 0x330002, 5, 0x340002, 6, 0x3D0002, 7, 0x440001, 0x320003, 0, 0 } }
    },
    {
    Shader::GeometryInfo,
    Shader::ModelViewProjectionMatrix,
    Shader::FogParameters,
    { Shader::RuntimeGeoPrimState, ";SetTransparencyMethod=EAGL::TM_OPAQUE;SetAlphaTestEnable=true;SetAlphaCompareValue=64;SetAlphaBlendMode=EAGL::ABM_OFF" },
    Shader::Sampler0, // global
    Shader::ModelMatrix,
    Shader::ViewMatrix,
    Shader::ProjectionMatrix,
    Shader::VertexData,
    Shader::IndexData
    }
    }
};

char const *TargetMVP2005::Name() {
    return "MVP2005";
}

int TargetMVP2005::Version() {
    return 4;
}

unsigned short TargetMVP2005::AnimVersion() {
    return 1284;
}

Shader *TargetMVP2005::Shaders() {
    return shaders_MVP2005;
}

unsigned int TargetMVP2005::NumShaders() {
    return std::size(shaders_MVP2005);
}

Shader *TargetMVP2005::DecideShader(MaterialProperties const &properties) {
    return DecideShader_MVP_2004_2005(this, properties);
}
